export const NICHE_RULES = {
  SaaS: [
    "saas",
    "software",
    "cloud",
    "crm",
    "erp",
    "app",
    "apps",
    "platform",
    "startup",
    "b2b",
    "automation",
    "hosting",
    "web tool",
  ],
  Tech: [
    "tech",
    "technology",
    "digital",
    "computer",
    "mobile",
    "gadget",
    "electronics",
    "cyber",
    "internet",
    "ai",
    "artificial intelligence",
  ],
  Business: [
    "business",
    "finance",
    "marketing",
    "entrepreneur",
    "startup",
    "corporate",
    "management",
    "invest",
    "investment",
  ],
  Food: [
    "food",
    "recipe",
    "restaurant",
    "kitchen",
    "cooking",
    "chef",
    "meal",
    "drink",
    "beverage",
  ],
  Health: [
    "health",
    "medical",
    "fitness",
    "wellness",
    "doctor",
    "hospital",
    "medicine",
    "nutrition",
    "dental",
  ],
  Travel: [
    "travel",
    "tour",
    "tourism",
    "hotel",
    "holiday",
    "vacation",
    "flight",
    "trip",
  ],
  Education: [
    "education",
    "school",
    "college",
    "university",
    "student",
    "learning",
    "academy",
    "course",
  ],
  "Home & Garden": [
    "home",
    "garden",
    "interior",
    "decor",
    "furniture",
    "property",
    "real estate",
    "construction",
  ],
  "Fashion & Beauty": [
    "fashion",
    "beauty",
    "style",
    "clothing",
    "apparel",
    "makeup",
    "skin",
    "jewelry",
  ],
  Sports: [
    "sport",
    "sports",
    "football",
    "cricket",
    "basketball",
    "soccer",
    "fitness sports",
  ],
  Entertainment: [
    "entertainment",
    "movie",
    "music",
    "celebrity",
    "gaming",
    "games",
    "film",
    "tv",
  ],
  News: ["news", "media", "daily", "journal", "press", "magazine"],
  Automotive: ["auto", "automotive", "car", "cars", "vehicle", "motor", "bike"],
  Crypto: ["crypto", "bitcoin", "blockchain", "web3", "forex"],
};
export const COUNTRY_GROUPS = {
  "United States": [
    "us",
    "usa",
    "u.s.",
    "u.s.a.",
    "united state",
    "united states",
    "united states of america",
  ],
  "United Kingdom": [
    "uk",
    "u.k.",
    "gb",
    "gbr",
    "united kingdom",
    "great britain",
  ],
  Bangladesh: ["bd", "bgd", "bangladesh"],
  Pakistan: ["pk", "pak", "pakistan"],
  India: ["in", "ind", "india"],
  Canada: ["ca", "can", "canada"],
  Australia: ["au", "aus", "australia"],
  "United Arab Emirates": ["ae", "uae", "u.a.e.", "united arab emirates"],
  Philippines: ["ph", "phl", "philippines", "phillipines", "philippine"],
  Indonesia: ["id", "idn", "indonesia"],
  Germany: ["de", "deu", "germany"],
  France: ["fr", "fra", "france"],
  Singapore: ["sg", "sgp", "singapore"],
  "New Zealand": ["nz", "nzl", "new zealand"],
};
